//! Fish species registry + a caught-fish instance.

use crate::season::{Season, TimeOfDay, WaterType};

#[derive(Clone, Copy, Debug)]
pub struct FishDef {
    pub id: u16,
    pub name: &'static str,
    pub glyph: char,
    pub seasons: &'static [Season],
    pub waters: &'static [WaterType],
    pub times: &'static [TimeOfDay],
    pub rarity: u8,       // 1 common .. 5 legendary
    pub size_min: u16,    // cm
    pub size_max: u16,    // cm (>= size_min)
    pub difficulty: u8,   // 1..10 reel-fight difficulty
    pub base_price: u32,  // gold at the average size
    pub bait_pref: u16,   // preferred bait id; 0 = no preference
}

use Season::*;
use TimeOfDay::*;
use WaterType::*;

const ALL_SEASONS: &[Season] = &[Spring, Summer, Fall, Winter];
const ALL_TIMES: &[TimeOfDay] = &[Dawn, Morning, Day, Dusk, Night];
const ALL_WATERS: &[WaterType] = &[Shallow, Deep, River, Marsh];

/// The whole species list. Ids must be unique and > 0.
pub static FISH: &[FishDef] = &[
    // --- Spring ---
    FishDef {
        id: 1,
        name: "Sunfin Panfish",
        glyph: 'p',
        seasons: &[Spring, Summer],
        waters: &[Shallow],
        times: &[Dawn, Morning, Day],
        rarity: 1,
        size_min: 8,
        size_max: 16,
        difficulty: 1,
        base_price: 4,
        bait_pref: 1, // Worm
    },
    FishDef {
        id: 2,
        name: "Spring Roach",
        glyph: 'r',
        seasons: &[Spring],
        waters: &[Shallow, River],
        times: &[Dawn, Morning],
        rarity: 1,
        size_min: 10,
        size_max: 22,
        difficulty: 2,
        base_price: 6,
        bait_pref: 1,
    },
    FishDef {
        id: 3,
        name: "Marsh Minnow",
        glyph: 'm',
        seasons: &[Spring, Summer, Fall],
        waters: &[Marsh],
        times: ALL_TIMES,
        rarity: 1,
        size_min: 6,
        size_max: 12,
        difficulty: 1,
        base_price: 3,
        bait_pref: 0,
    },
    FishDef {
        id: 4,
        name: "Blossom Trout",
        glyph: 't',
        seasons: &[Spring],
        waters: &[River],
        times: &[Dawn, Dusk],
        rarity: 2,
        size_min: 20,
        size_max: 38,
        difficulty: 4,
        base_price: 18,
        bait_pref: 3, // Cricket
    },
    FishDef {
        id: 5,
        name: "Speckled Dace",
        glyph: 'd',
        seasons: &[Spring, Fall],
        waters: &[River, Shallow],
        times: &[Morning, Day],
        rarity: 1,
        size_min: 9,
        size_max: 18,
        difficulty: 2,
        base_price: 5,
        bait_pref: 0,
    },
    FishDef {
        id: 6,
        name: "Frogmouth Bass",
        glyph: 'b',
        seasons: &[Spring, Summer],
        waters: &[Marsh, Shallow],
        times: &[Dusk, Night],
        rarity: 2,
        size_min: 24,
        size_max: 45,
        difficulty: 5,
        base_price: 22,
        bait_pref: 2, // Grub
    },
    FishDef {
        id: 7,
        name: "Emerald Chub",
        glyph: 'c',
        seasons: &[Spring, Summer, Fall],
        waters: &[Shallow, River],
        times: ALL_TIMES,
        rarity: 1,
        size_min: 10,
        size_max: 20,
        difficulty: 1,
        base_price: 5,
        bait_pref: 0,
    },
    // --- Summer ---
    FishDef {
        id: 8,
        name: "Golden Carp",
        glyph: 'C',
        seasons: &[Summer, Fall],
        waters: &[Deep, Shallow],
        times: &[Day, Dusk],
        rarity: 2,
        size_min: 30,
        size_max: 60,
        difficulty: 5,
        base_price: 28,
        bait_pref: 1,
    },
    FishDef {
        id: 9,
        name: "Sunburst Bluegill",
        glyph: 'g',
        seasons: &[Summer],
        waters: &[Shallow],
        times: &[Morning, Day],
        rarity: 1,
        size_min: 8,
        size_max: 15,
        difficulty: 1,
        base_price: 4,
        bait_pref: 1,
    },
    FishDef {
        id: 10,
        name: "River Pike",
        glyph: 'P',
        seasons: &[Summer, Fall],
        waters: &[River, Deep],
        times: &[Dawn, Dusk, Night],
        rarity: 3,
        size_min: 45,
        size_max: 85,
        difficulty: 7,
        base_price: 55,
        bait_pref: 4, // Shrimp
    },
    FishDef {
        id: 11,
        name: "Cattail Perch",
        glyph: 'e',
        seasons: &[Summer, Fall],
        waters: &[Marsh],
        times: &[Morning, Day, Dusk],
        rarity: 1,
        size_min: 12,
        size_max: 24,
        difficulty: 2,
        base_price: 7,
        bait_pref: 0,
    },
    FishDef {
        id: 12,
        name: "Silverjaw Herring",
        glyph: 'h',
        seasons: &[Summer],
        waters: &[Deep],
        times: &[Dawn, Morning],
        rarity: 2,
        size_min: 18,
        size_max: 34,
        difficulty: 3,
        base_price: 15,
        bait_pref: 5, // Roe
    },
    FishDef {
        id: 13,
        name: "Firefly Gar",
        glyph: 'f',
        seasons: &[Summer],
        waters: &[Marsh, River],
        times: &[Night],
        rarity: 3,
        size_min: 40,
        size_max: 70,
        difficulty: 6,
        base_price: 40,
        bait_pref: 6, // Glowbait
    },
    FishDef {
        id: 14,
        name: "Deepwater Sturgeon",
        glyph: 'S',
        seasons: &[Summer, Fall, Winter],
        waters: &[Deep],
        times: &[Night, Dawn],
        rarity: 4,
        size_min: 70,
        size_max: 130,
        difficulty: 9,
        base_price: 120,
        bait_pref: 5,
    },
    // --- Fall ---
    FishDef {
        id: 15,
        name: "Amber Walleye",
        glyph: 'w',
        seasons: &[Fall],
        waters: &[Deep, River],
        times: &[Dusk, Night],
        rarity: 3,
        size_min: 35,
        size_max: 65,
        difficulty: 6,
        base_price: 38,
        bait_pref: 4,
    },
    FishDef {
        id: 16,
        name: "Harvest Catfish",
        glyph: 'k',
        seasons: &[Fall, Summer],
        waters: &[Marsh, Deep],
        times: &[Night],
        rarity: 3,
        size_min: 50,
        size_max: 95,
        difficulty: 7,
        base_price: 48,
        bait_pref: 2,
    },
    FishDef {
        id: 17,
        name: "Rustfin Shiner",
        glyph: 's',
        seasons: &[Fall],
        waters: &[Shallow, River],
        times: &[Morning, Day],
        rarity: 1,
        size_min: 9,
        size_max: 17,
        difficulty: 1,
        base_price: 4,
        bait_pref: 0,
    },
    FishDef {
        id: 18,
        name: "Copperback Salmon",
        glyph: 'l',
        seasons: &[Fall],
        waters: &[River],
        times: &[Dawn, Morning, Dusk],
        rarity: 3,
        size_min: 40,
        size_max: 75,
        difficulty: 7,
        base_price: 50,
        bait_pref: 3,
    },
    FishDef {
        id: 19,
        name: "Foggy Eel",
        glyph: 'E',
        seasons: &[Fall],
        waters: &[Marsh],
        times: &[Dusk, Night],
        rarity: 3,
        size_min: 45,
        size_max: 80,
        difficulty: 6,
        base_price: 42,
        bait_pref: 2,
    },
    FishDef {
        id: 20,
        name: "Acorn Perch",
        glyph: 'a',
        seasons: &[Fall],
        waters: &[Shallow, Marsh],
        times: ALL_TIMES,
        rarity: 1,
        size_min: 10,
        size_max: 19,
        difficulty: 2,
        base_price: 6,
        bait_pref: 0,
    },
    // --- Winter ---
    FishDef {
        id: 21,
        name: "Frostgill Trout",
        glyph: 'T',
        seasons: &[Winter],
        waters: &[River, Deep],
        times: &[Day, Dusk],
        rarity: 2,
        size_min: 22,
        size_max: 42,
        difficulty: 4,
        base_price: 20,
        bait_pref: 1,
    },
    FishDef {
        id: 22,
        name: "Icevein Char",
        glyph: 'i',
        seasons: &[Winter],
        waters: &[Deep],
        times: &[Dawn, Day],
        rarity: 3,
        size_min: 28,
        size_max: 55,
        difficulty: 5,
        base_price: 32,
        bait_pref: 5,
    },
    FishDef {
        id: 23,
        name: "Snowdrift Smelt",
        glyph: 'n',
        seasons: &[Winter],
        waters: &[Shallow, Marsh],
        times: ALL_TIMES,
        rarity: 1,
        size_min: 7,
        size_max: 13,
        difficulty: 1,
        base_price: 3,
        bait_pref: 0,
    },
    FishDef {
        id: 24,
        name: "Glacierscale Pike",
        glyph: 'K',
        seasons: &[Winter],
        waters: &[River, Deep],
        times: &[Night, Dawn],
        rarity: 4,
        size_min: 60,
        size_max: 100,
        difficulty: 8,
        base_price: 85,
        bait_pref: 6,
    },
    FishDef {
        id: 25,
        name: "Hollow Moonfish",
        glyph: 'o',
        seasons: &[Winter, Fall],
        waters: &[Marsh],
        times: &[Night],
        rarity: 4,
        size_min: 30,
        size_max: 58,
        difficulty: 7,
        base_price: 70,
        bait_pref: 6,
    },
    // --- Legendary, all-season rarities ---
    FishDef {
        id: 26,
        name: "Old Man of the Lake",
        glyph: 'O',
        seasons: ALL_SEASONS,
        waters: &[Deep],
        times: &[Night],
        rarity: 5,
        size_min: 110,
        size_max: 140,
        difficulty: 10,
        base_price: 300,
        bait_pref: 6,
    },
    FishDef {
        id: 27,
        name: "Marsh Wraithfin",
